# Generated by Django 5.0 on 2025-01-03 02:02

import django.db.models.deletion
import documentation.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0002_document_views_count_and_more"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_type",
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_size",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to=documentation.models.attachment_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documentation.category",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
