# Generated by Django 5.0 on 2025-01-03 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documentation",
            "0003_alter_attachment_options_remove_category_parent_and_more",
        ),
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="documentati_updated_22b2a9_idx",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_public"], name="documentati_is_publ_e886ca_idx"
            ),
        ),
    ]
