# Generated by Django 5.0 on 2025-01-03 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documentation",
            "0004_remove_document_documentati_updated_22b2a9_idx_and_more",
        ),
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["order", "title"]},
        ),
        migrations.AddField(
            model_name="document",
            name="is_index",
            field=models.BooleanField(
                default=False,
                help_text="Whether this document is the main page of its section",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documentation.document",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["order"], name="documentati_order_52bd8d_idx"),
        ),
    ]
